server:
  port: 8080

management.endpoints.web.exposure.include: health,info
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.labs64: DEBUG
    org.springframework.cloud.stream: INFO

pipelines: []
#  - name: 'logs'
#    enabled: true
#    transformer:
#      name: 'zero'
#    processor:
#      name: 'logging_processor'
#      clazz: 'io.labs64.cart.processors.LoggingProcessor'
#      properties:
#        log-level: "DEBUG"

spring:
  application:
    name: labs64.io-shopping-cart
  cloud:
    stream:
      bindings:
        shopping-cart-out-0:
          destination: labs64-shopping-cart-topic
          binder: rabbit
        shopping-cart-in-0:
          destination: labs64-shopping-cart-topic
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
      rabbit:
        bindings:
          shopping-cart-out-0:
            producer:
              exchangeType: topic
          shopping-cart-in-0:
            consumer:
              autoBindDlq: true

  messages:
    basename: messages
    fallback-to-system-locale: false
    encoding: UTF-8

  rabbitmq:
    host: rabbitmq.default.svc.cluster.local
    port: 5672
    username:
    password:

  data:
    redis:
      host: redis-master.default.svc.cluster.local
      port: 6379
      timeout: 60000
      password: ""
      database: 0
      ssl:
        enabled: true

cart:
  prefix: "shopping-cart:"
  ttl: PT6H
  currency:
    - USD
    - EUR
